import { actions, careerTracks, factions, mentors, statMeta } from "../game/data.js";
import { canAdvance } from "../game/engine.js";

export function GameScreen({ state, onAction, onTask, onAdvance }) {
  const career = careerTracks.find((track) => track.id === state.careerTrack);
  const mentor = mentors[state.mentorPersonality];
  const faction = factions[state.faction];
  const { weeklyTasks } = state;
  return <><header className="bg-slate-900 text-white px-4 py-4"><div className="max-w-5xl mx-auto flex flex-wrap items-center gap-x-4 gap-y-2 text-sm"><strong className="text-lg">{state.playerName}</strong><span>实习生</span><span>{career.icon} {career.subRoles.find((role) => role.id === state.subRole)?.name}</span><span>{mentor.icon} {mentor.name}</span><span>{faction.icon} {faction.name}</span><span className="ml-auto">第 {state.week} / {state.totalWeeks} 周</span></div></header><main className="max-w-5xl mx-auto px-4 py-8 grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-800">📊 属性面板</h3><div className="space-y-3 mt-4">{statMeta.map(([key, icon, name, desc]) => <div key={key}><div className="flex justify-between text-sm"><span>{icon} {name}</span><strong>{key === "money" ? `¥${state.stats[key]}` : state.stats[key]}</strong></div><p className="text-[11px] text-slate-400">{desc}</p></div>)}</div></aside><section><div className="flex items-center justify-between mb-4"><h3 className="font-bold text-slate-800">🎮 操作面板 第{state.week}/{state.totalWeeks}周</h3><span className="text-xs text-slate-500">本周必做 {weeklyTasks.eventCompleted + weeklyTasks.messageCompleted}/{weeklyTasks.eventCount + weeklyTasks.messageCount}</span></div><div className="grid gap-3">{actions.map((action) => <button key={action.id} onClick={() => onAction(action.id)} className="rounded-xl border border-slate-200 bg-white p-4 text-left hover:border-indigo-300 hover:shadow-md transition-all"><strong>{action.icon} {action.name}</strong><p className="text-sm text-slate-500 mt-1">{action.description}</p><p className="text-xs text-indigo-500 mt-2">{Object.entries(action.effects).map(([key, value]) => `${key} ${value > 0 ? "+" : ""}${value}`).join(" · ")}</p></button>)}</div><div className="grid gap-3 sm:grid-cols-2 mt-5"><button onClick={() => onTask("event")} className="rounded-lg bg-slate-100 p-3 text-sm">🎲 看看发生了什么 ({weeklyTasks.eventCompleted}/{weeklyTasks.eventCount})</button><button onClick={() => onTask("message")} className="rounded-lg bg-slate-100 p-3 text-sm">💬 查看消息 ({weeklyTasks.messageCompleted}/{weeklyTasks.messageCount})</button></div><button disabled={!canAdvance(state)} onClick={onAdvance} className="w-full mt-5 rounded-lg bg-indigo-600 py-3 text-white font-bold disabled:opacity-40">{canAdvance(state) ? `➡️ 进入第${state.week + 1}周` : "🔒 完成必做任务后解锁"}</button><div className="mt-5 rounded-xl bg-slate-50 p-4 max-h-52 overflow-auto space-y-2">{state.log.map((entry, index) => <p key={`${entry}-${index}`} className="text-sm text-slate-600">{entry}</p>)}</div></section></main></>;
}
